import { addToast, Divider } from '@heroui/react'
import Image from 'next/image'
import Link from 'next/link'
import { FaImage, FaRegCopy } from 'react-icons/fa'

const CodeWithSelection = ({ label, code }: { label: string; code: string }) => {
  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text).then(() => {
      addToast({
        title: 'Copied to clipboard',
        color: 'success',
        timeout: 2000,
      })
    })
  }

  return (
    <>
      <div className='flex flex-col group'>
        <p className='font-semibold mb-1'>{label}</p>
        <div
          className='flex justify-between items-center gap-4 bg-[#1c1c1c] hover:bg-[#1f1f1f] p-3 rounded w-full lg:w-[70%] cursor-pointer duration-150 min-w-0'
          onClick={() => copyToClipboard(code)}
        >
          <p className='text-xs font-mono w-[95%] overflow-hidden'>{code}</p>
          <FaRegCopy className='text-lg shrink-0 w-6 group-hover:opacity-70 duration-150' />
        </div>
      </div>
    </>
  )
}

export default function ShareableImage({ id }: { id: string }) {
  return (
    <div className='flex flex-col w-full mt-14'>
      <div className='flex justify-between items-center'>
        <div className='flex items-center gap-2'>
          <FaImage fontSize={22} />
          <p className='text-lg font-semibold py-2'>Steeeam Card</p>
        </div>
      </div>

      <Divider className='w-full h-px bg-light-border mb-5 lg:mb-5' />

      <div className='flex flex-col w-full gap-4'>
        <div className='w-full lg:max-w-[70%]'>
          <Link href={`/api/${id}`} target='_blank'>
            <Image
              src={`/api/${id}`}
              width={705}
              height={385}
              alt='Steeeam Card'
              className='rounded-md border border-light-border w-full hover:border-hover-border duration-150'
            />
          </Link>

          <p className='text-xs md:text-sm'>
            This image can be fully customized to your liking.{' '}
            <Link
              href={'https://github.com/zevnda/steeeam?tab=readme-ov-file#customize-your-steeeam-card'}
              target='_blank'
            >
              Learn more.
            </Link>
          </p>
        </div>

        <div className='flex flex-col space-y-4'>
          <CodeWithSelection label='Discord' code={`https://steeeam.vercel.app/api/${id}`} />
          <CodeWithSelection label='Twitter, Facebook, WhatsApp, etc..' code={`https://steeeam.vercel.app/${id}`} />
          <CodeWithSelection
            label='HTML'
            code={`<a href="https://steeeam.vercel.app/${id}"> <img src="https://steeeam.vercel.app/api/${id}" alt="Generate by Steeeam"/></a>`}
          />
          <CodeWithSelection
            label='Markdown'
            code={`[![Generated by Steeeam](https://steeeam.vercel.app/api/${id})](https://steeeam.vercel.app)`}
          />
          <CodeWithSelection
            label='BBCode'
            code={`[url=https://steeeam.vercel.app/${id}][img]https://steeeam.vercel.app/api/${id}[/img][/url]`}
          />
        </div>
      </div>
    </div>
  )
}
